Code/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|

// Para Desabilitar la gestion de creacion de usuarios.
Route::get('register', 'Auth\AuthController@showRegistrationForm');
Route::post('register', 'Auth\AuthController@register');

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', 'Auth\AuthController@logout');

// Registration Routes...
$this->get('register', 'Auth\AuthController@showRegistrationForm');
$this->post('register', 'Auth\AuthController@register');

// Password Reset Routes...
$this->get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
$this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
$this->post('password/reset', 'Auth\PasswordController@reset');

Route::auth();
*/

Route::get('/','HomeController@index');

Route::get('login', 'Auth\AuthController@showLoginForm');

Route::post('login', 'Auth\AuthController@login');

Route::get('logout', 'Auth\AuthController@logout');

// Route::group(['perms' => 'ver-examenes-crear'], function (){
//      Route::resource('examenes','ExamenesController', ['except' => ['update']]);
//      Route::post('tomarexamen/{id}/notificar','TomarExamenController@notificar');
//      Route::post('api/preguntas/getData/{action}','PreguntasController@getData');
//      Route::post('api/opciones/getData/{action}','OpcionesController@getData');
//      Route::post('api/examenes/guardar/{id}/{campo}/{valor}','ExamenesController@guardar');
//      Route::post('api/permisos/getData/{action}','PermisosController@getData');
//      Route::post('api/permisos/getOption/{action}','PermisosController@getOption');
//      Route::get('permisos',['uses'=>'PermisosController@index','as'=>'permisos.index']);
//      Route::get('examenes/{id}/importexcel', 'ExamenesController@ImportExcel');
//      Route::post('examenes/{id}/importexcelpost', 'ExamenesController@ImportExcelPost');
// });

// Route::group(['perms' => 'ver-tomar'], function (){
//      Route::resource('tomarexamen','TomarExamenController',['except'=>['store','destroy']]);
// });

Route::group(['perms' => 'ver-usuarios'], function (){
     Route::resource('users','UserController');
     Route::post('usuarios/{id}/notificar','UsuariosController@notificar');
});

Route::group(['perms' => 'view-tenants'], function (){
     Route::resource('tenants','TenantsController');     
});

Route::group(['perms' => 'view-expences'], function (){
     Route::resource('expence','ExpencesController');
});

Route::group(['perms' => 'view-expenceType'], function (){
     Route::resource('expenceTypes','ExpenceTypesController');
});

Route::group(['perms' => 'ver-roles'], function (){
     Route::get('roles',['as'=>'roles.index','uses'=>'RoleController@index']);
     Route::get('roles/create',['as'=>'roles.create','uses'=>'RoleController@create']);
     Route::post('roles/create',['as'=>'roles.store','uses'=>'RoleController@store']);
     Route::get('roles/{id}',['as'=>'roles.show','uses'=>'RoleController@show']);
     Route::get('roles/{id}/edit',['as'=>'roles.edit','uses'=>'RoleController@edit',]);
     Route::patch('roles/{id}',['as'=>'roles.update','uses'=>'RoleController@update',]);
     Route::delete('roles/{id}',['as'=>'roles.destroy','uses'=>'RoleController@destroy',]);
});

Route::group(['perms' => 'edit-my-user'], function (){
     Route::get('usuarios/{id}/edit',['as'=>'usuarios.edit','uses'=>'UsuariosController@edit',]);
     Route::patch('usuarios/{id}',['as'=>'usuarios.update','uses'=>'UsuariosController@update',]);
});

Code/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="google" content="notranslate">
		<meta http-equiv="Content-Language" content="en">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Expence Manager - Autenticated User</title>

		<!-- Fonts -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

		<!-- Styles -->
		{!! Html::style('css/bootstrap.css') !!}
		{!! Html::style('css/site.css') !!}

		<style>
			body {
				font-family: 'Lato';
				padding-top: 0px !important;
			}

			.fa-btn {
				margin-right: 6px;
			}

			.popover {
				max-width: 900px !important;
				word-wrap: break-word;
			}
		</style>
	</head>
	<body id="app-layout">
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">

					<!-- Collapsed Hamburger -->
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
						<span class="sr-only">Toggle Navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<!-- Branding Image -->
					<a class="navbar-brand" href="{{ url('/') }}">
						Expences
					</a>
				</div>

				<div class="collapse navbar-collapse" id="app-navbar-collapse">
					<!-- Left Side Of Navbar -->
					@if (Auth::guest())
					<span></span>
					@else
					<ul class="nav navbar-nav">
						<li><a href="{{ url('/') }}">Home</a></li>
						@can('perms',['view-expences'])
							<li><a href="{{ route('expence.index') }}">Expences</a></li>
						@endcan
						@can('perms',['ver-usuarios','ver-roles','view-tenants','view-expences','view-expenceType'])
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								Administracion <span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								@can('perms',['ver-usuarios'])
									<li><a href="{{ route('users.index') }}">Usuarios</a></li>
									<li role="separator" class="divider"></li>
								@endcan
								@can('perms',['ver-roles'])
									<li><a href="{{ route('roles.index') }}">Roles</a></li>
									<li role="separator" class="divider"></li>
								@endcan
								@can('perms',['view-tenants'])
									<li><a href="{{ route('tenants.index') }}">Tenants</a></li>
									<li role="separator" class="divider"></li>
								@endcan
								@can('perms',['view-expenceType'])
									<li><a href="{{ route('expenceTypes.index') }}">Types</a></li>
								@endcan
							</ul>
						</li>
						@endcan
					</ul>
					@endif
					<!-- Right Side Of Navbar -->
					<ul class="nav navbar-nav navbar-right">
						<!-- Authentication Links -->
						@if (Auth::guest())
						<li><a href="{{ url('/login') }}">Login</a></li>
						@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
								<i class="fa fa-user fa-fw"></i> {{ Auth::user()->name }} <span class="caret"></span>
							</a>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="{{ url('/usuarios/' . Auth::user() -> id . '/edit' ) }}">
										<i class="fa fa-btn fa-user-md" aria-hidden="true"></i>Password
									</a>
								</li>
								<li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
							</ul>

						</li>
						@endif
					</ul>
				</div>
			</div>
		</nav>

		@yield('content')

		<!-- JavaScripts -->
		{!! Html::script('js/jquery-2.2.3.min.js') !!}
		{!! Html::script('js/bootstrap.min.js') !!}
		@yield('scripts')
		<script type="text/javascript">
			$(document).ready(function() {
				$('.navbar-collapse a[href="'+location.href+'"]').parents('li').addClass('active');
				$('[data-toggle="popover"]').popover();
			});
		</script>

		<!-- Modal -->
		<div class="modal fade" id="myModalPopUp1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h3 class="modal-title"></h3>
					</div>
					<div class="modal-body">
						<form>
							<div class="form-group">
								<label for="exampleInputEmail1">Material 1</label>
								<input type="text" class="form-control" id="exampleInputEmail1" placeholder="Material 1">
							</div>
							<div class="form-group">
								<label for="exampleInputEmail2">Material 2</label>
								<input type="text" class="form-control" id="exampleInputEmail2" placeholder="Material 2">
							</div>
							<div class="form-group">
								<label for="exampleInputEmail3">Material 3</label>
								<input type="text" class="form-control" id="exampleInputEmail3" placeholder="Material 3">
							</div>
							<div class="form-group">
								<label for="exampleInputEmail4">Material 4</label>
								<input type="text" class="form-control" id="exampleInputEmail4" placeholder="Material 4">
							</div>
						</form>
					</div>
					<!--<div class="modal-footer">-->
					<!--    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
					<!--    <button type="button" class="btn btn-primary">Save changes</button>-->
					<!--</div>-->
				</div>
			</div>
		</div>
	</body>
</html>

Code/resources/views/layouts/popup.blade.php
    @yield('content')
    @yield('scripts')