Code/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|

// Para Desabilitar la gestion de creacion de usuarios.
Route::get('register', 'Auth\AuthController@showRegistrationForm');
Route::post('register', 'Auth\AuthController@register');

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', 'Auth\AuthController@logout');

// Registration Routes...
$this->get('register', 'Auth\AuthController@showRegistrationForm');
$this->post('register', 'Auth\AuthController@register');

// Password Reset Routes...
$this->get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
$this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
$this->post('password/reset', 'Auth\PasswordController@reset');

Route::auth();
*/

Route::get('/','HomeController@index');

Route::get('login', 'Auth\AuthController@showLoginForm');

Route::post('login', 'Auth\AuthController@login');

Route::get('logout', 'Auth\AuthController@logout');

// Route::group(['perms' => 'ver-examenes-crear'], function (){
//      Route::resource('examenes','ExamenesController', ['except' => ['update']]);
//      Route::post('tomarexamen/{id}/notificar','TomarExamenController@notificar');
//      Route::post('api/preguntas/getData/{action}','PreguntasController@getData');
//      Route::post('api/opciones/getData/{action}','OpcionesController@getData');
//      Route::post('api/examenes/guardar/{id}/{campo}/{valor}','ExamenesController@guardar');
//      Route::post('api/permisos/getData/{action}','PermisosController@getData');
//      Route::post('api/permisos/getOption/{action}','PermisosController@getOption');
//      Route::get('permisos',['uses'=>'PermisosController@index','as'=>'permisos.index']);
//      Route::get('examenes/{id}/importexcel', 'ExamenesController@ImportExcel');
//      Route::post('examenes/{id}/importexcelpost', 'ExamenesController@ImportExcelPost');
// });

// Route::group(['perms' => 'ver-tomar'], function (){
//      Route::resource('tomarexamen','TomarExamenController',['except'=>['store','destroy']]);
// });

Route::group(['perms' => 'ver-usuarios'], function (){
     Route::resource('users','UserController');
     Route::post('usuarios/{id}/notificar','UsuariosController@notificar');
});

Route::group(['perms' => 'view-tenants'], function (){
     Route::resource('tenants','TenantsController');     
});

Route::group(['perms' => 'view-expences'], function (){
     Route::resource('expence','ExpencesController');
});

Route::group(['perms' => 'view-expenceType'], function (){
     Route::resource('expenceTypes','ExpenceTypesController');
});

Route::group(['perms' => 'ver-roles'], function (){
     Route::get('roles',['as'=>'roles.index','uses'=>'RoleController@index']);
     Route::get('roles/create',['as'=>'roles.create','uses'=>'RoleController@create']);
     Route::post('roles/create',['as'=>'roles.store','uses'=>'RoleController@store']);
     Route::get('roles/{id}',['as'=>'roles.show','uses'=>'RoleController@show']);
     Route::get('roles/{id}/edit',['as'=>'roles.edit','uses'=>'RoleController@edit',]);
     Route::patch('roles/{id}',['as'=>'roles.update','uses'=>'RoleController@update',]);
     Route::delete('roles/{id}',['as'=>'roles.destroy','uses'=>'RoleController@destroy',]);
});

Route::group(['perms' => 'edit-my-user'], function (){
     Route::get('usuarios/{id}/edit',['as'=>'usuarios.edit','uses'=>'UsuariosController@edit',]);
     Route::patch('usuarios/{id}',['as'=>'usuarios.update','uses'=>'UsuariosController@update',]);
});

Code/app/ExpenceTypes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ExpenceTypes extends Model
{
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [
		'name'
	];

	protected $table = "expenceTypes";

}

Code/app/Expences.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Expences extends Model
{
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = 
	[
		'name',
		'typeId',
		'description',
		'notes',
		'dueDate',
		'tenantId',
		'userId',
		'amount'
	];

	protected $table = "expences";

	public function type()
    {
        return $this->hasOne('App\ExpenceTypes', 'id', 'typeId');
	}
	
	public function user()
    {
        return $this->hasOne('App\User', 'id', 'userId');
	}
	
	public function tenant()
    {
        return $this->hasOne('App\Tenants', 'id', 'tenantId');
    }

}

Code/app/Http/Controllers/ExpencesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Expences;
use App\ExpenceTypes;
use App\User;
use DB;
use Hash;
use Mail;
use Auth;
use Redirect;

class ExpencesController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}
	/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	public function index(Request $request)
	{
		$tenantId = User::find(Auth::id())
			 	-> tenants()
			 	-> first()
			 	-> id;

		$data = Expences::where('tenantId',$tenantId)->orderBy('id','DESC')->paginate(5);
		return view('expences.index',compact('data'))
			->with('i', ($request->input('page', 1) - 1) * 5);
	}

	/**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
	public function create()
	{
		$expenceTypes = ExpenceTypes::orderBy('id','DESC')->lists('name','id');
		return view('expences.create',compact('expenceTypes'));
	}

	/**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
	public function store(Request $request)
	{
		$this->validate($request, [
			'typeId' => 'required',
			'description' => 'required',
			'amount' => 'required'
		]);

		$userId = Auth::id();
		$tenantId = User::find($userId)
			 	-> tenants()
			 	-> first()
			 	-> id;
		
		$input = $request->all();
		$input['userId'] = $userId;
		$input['tenantId'] = $tenantId;

		$expence = Expences::create($input);

		return redirect()
			->route('expence.index')
			->with('success','Expences created successfully');
	}

	/**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
	public function show($id)
	{
		$expence = Expences::find($id);
		return view('expences.show',compact('expence'));
	}

	/**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
	public function edit($id)
	{
		$expence = Expences::find($id);
		$expenceTypes = ExpenceTypes::orderBy('id','DESC')->lists('name','id');
		return view('expences.edit',compact('expence','expenceTypes'));
	}

	/**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
	public function update(Request $request, $id)
	{
		$this->validate($request, [
			'typeId' => 'required',
			'description' => 'required',
			'amount' => 'required'
		]);

		$input = $request->all();
		$expence = Expences::find($id);
		$expence->update($input);

		return redirect()
			->route('expence.index')
			->with('success','Expences updated successfully');
	}

	/**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
	public function destroy($id)
	{
		Expences::find($id)->delete();
		return redirect()
			->route('expence.index')
			->with('success','Expences deleted successfully');
	}
}

Code/resources/views/expences/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-lg-12 margin-tb">
			<div class="pull-left">
				<h2>Crear Nuevo Expence</h2>
			</div>
			<div class="pull-right">
				<a class="btn btn-primary" href="{{ route('expence.index') }}"> Atras</a>
			</div>
		</div>
	</div>
	@if (count($errors) > 0)
	<div class="alert alert-danger">
		<strong>Whoops!</strong> There were some problems with your input.<br><br>
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
	@endif
	{!! Form::open(array('route' => 'expences.store','method'=>'POST')) !!}
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Tipo:</strong>
				{!! Form::select('typeId', $expenceTypes, null, array('placeholder' => 'Tipo','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Vencimiento:</strong>
				{!! Form::date('dueDate', \Carbon\Carbon::now(), array('placeholder' => 'Vencimiento','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Descripcion:</strong>
				{!! Form::textarea('description', null, array('placeholder' => 'Descripcion','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Descripcion:</strong>
				{!! Form::number('amount', null, array('placeholder' => 'Amount','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Notas:</strong>
				{!! Form::textarea('notes', null, array('placeholder' => 'Notas','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12 text-center">
			<button type="submit" class="btn btn-primary">Guardar</button>
		</div>
	</div>
	{!! Form::close() !!}
</div>
@endsection

Code/resources/views/expences/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-lg-12 margin-tb">
			<div class="pull-left">
				<h2>Editar Expence</h2>
			</div>
			<div class="pull-right">
				<a class="btn btn-primary" href="{{ route('expence.index') }}"> Atras</a>
			</div>
		</div>
	</div>
	@if (count($errors) > 0)
	<div class="alert alert-danger">
		<strong>Whoops!</strong> There were some problems with your input.<br><br>
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
	@endif
	{!! Form::model($expence, ['method' => 'PATCH','route' => ['expences.update', $expence->id]]) !!}
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Tipo:</strong>
				{!! Form::select('typeId', $expenceTypes, null, array('placeholder' => 'Tipo','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Vencimiento:</strong>
				{!! Form::date('dueDate', \Carbon\Carbon::now(), array('placeholder' => 'Vencimiento','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Descripcion:</strong>
				{!! Form::number('amount', null, array('placeholder' => 'Amount','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Descripcion:</strong>
				{!! Form::textarea('description', null, array('placeholder' => 'Descripcion','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<strong>Notas:</strong>
				{!! Form::textarea('notes', null, array('placeholder' => 'Notas','class' => 'form-control')) !!}
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12 text-center">
			<button type="submit" class="btn btn-primary">Guardar</button>
		</div>
	</div>
	{!! Form::close() !!}
</div>
@endsection

Code/resources/views/expences/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-lg-12 margin-tb">
			<div class="pull-left">
				<h2>Administracion de expences</h2>
			</div>
			<div class="pull-right">
				<a class="btn btn-success" href="{{ route('expence.create') }}"> Crear Nuevo expence</a>
			</div>
		</div>
	</div>
	@if ($message = Session::get('success'))
	<div class="alert alert-success">
		<p>{{ $message }}</p>
	</div>
	@endif
	<table class="table table-bordered">
		<tr>
			<th>No</th>
			<th>Tipo</th>
			<th>Description</th>
			<th>Vencimiento</th>
			<th>Usuario</th>
			<th>Fecha</th>
			<th width="290px">Accion</th>
		</tr>
		@foreach ($data as $key => $expence)
		<tr>
			<td>{{ ++$i }}</td>
			<td>{{ $expence->type -> name }}</td>
			<td>{{ $expence->description }}</td>
			<td>{{ $expence->dueDate }}</td>
			<td>{{ $expence->user -> name }}</td>
			<td>{{ $expence->created_at }}</td>
			<td>
				<a class="btn btn-info" href="{{ route('expence.show',$expence->id) }}">Ver</a>
				<a class="btn btn-primary" href="{{ route('expence.edit',$expence->id) }}">Editar</a>
				{!! Form::open([
					'method' => 'DELETE',
					'route' => ['expence.destroy', $expence->id],
					'style'=>'display:inline'
					]) !!}
				{!! Form::submit('Eliminar', ['class' => 'btn btn-danger']) !!}
				{!! Form::close() !!}
			</td>
		</tr>
		@endforeach
	</table>
	{!! $data->render() !!}
</div>
@endsection

Code/resources/views/expences/show.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
	<div class="row">
	    <div class="col-lg-12 margin-tb">
	        <div class="pull-left">
	            <h2> Ver Expences</h2>
	        </div>
	        <div class="pull-right">
	            <a class="btn btn-primary" href="{{ route('expence.index') }}"> Atras</a>
	        </div>
	    </div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipo:</strong>
                {{ $expence->type->name }}
            </div>
        </div>
		<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Descripcion:</strong>
                {{ $expence->description }}
            </div>
        </div>
		<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Vencimiento:</strong>
                {{ $expence->dueDate }}
            </div>
        </div>
		<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Usuario:</strong>
                {{ $expence->user->name }}
            </div>
        </div>
		<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Fecha:</strong>
                {{ $expence->created_at }}
            </div>
        </div>
	</div>
</div>
@endsection